jyqj/backend/teacher/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from backend.accounts.perms import perm_required
from .views import teacher_list, teacher_edit, TeacherDTView, get_teacher_by_mobile, course_system_choices_v
teacher_urls = [
    url(r'^teacher_list/$', perm_required(['teacher.can_view'])(teacher_list), name='teacher_list'),
    url(r'^datatable/$', TeacherDTView.as_view(), name='datatable'),
    url(r'^get_teacher_name', get_teacher_by_mobile, name='teacher_name'),
    url(r'^teacher_list/teacher_create/$', perm_required(['teacher.can_create'])(teacher_edit), name='teacher_create'),
    url(r'^teacher_list/teacher_modify/(\d+)/$', perm_required(['teacher.can_modify'])(teacher_edit), name='teacher_modify'),
    url(r'^course_system_choices/$', course_system_choices_v, name='course_system_choices'),
    
]

jyqj/jyqj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from backend.accounts.urls import account_urls
from backend.simple.urls import simple_urls
from backend.accounts.views import index
from backend.upload.urls import upload_urls
from backend.institution.urls import institution_urls
from backend.musicballoon.urls import musicballoon_urls
from backend.teacher.urls import teacher_urls
from backend.video.urls import video_urls
from backend.score.urls import score_urls
from backend.operation_log.urls import operationlog_urls

from backend.bukaopu.urls import bkp_urls

from backend.score_optional.urls import score_optional_urls
from backend.score_enjoy.urls import score_enjoy_urls
from backend.classes.urls import class_urls
from backend.student.urls import student_urls
from backend.unit.urls import unit_urls
from backend.course.urls import course_urls
from backend.hzq_score.urls import hzq_score_urls
from backend.teacher_version.urls import teacherversion_urls
from backend.course_system.urls import course_system_urls
from backend.wechart.urls import wechart_urls



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(account_urls, namespace='accounts')),
    url(r'^simple/', include(simple_urls, namespace='simple')),
    url(r'^institution/', include(institution_urls, namespace='institution')),
    url(r'^musicballoon/', include(musicballoon_urls, namespace='musicballoon')),
    url(r'^bkp/', include(bkp_urls, namespace='bukaopu')),
    url(r'^upload/', include(upload_urls, namespace='upload')),
    url(r'^teacher/', include(teacher_urls, namespace='teacher')),
    url(r'^video/', include(video_urls, namespace='video')),
    url(r'^score/', include(score_urls, namespace='score')),
    url(r'^hzqscore/', include(hzq_score_urls, namespace='hzqscore')),
    url(r'^operationlog/', include(operationlog_urls, namespace='operationlog')),

    url(r'^score_optional/', include(score_optional_urls, namespace='score_optional')),
    url(r'^score_enjoy/', include(score_enjoy_urls, namespace='score_enjoy')),
    url(r'^class/', include(class_urls, namespace='class')),
    url(r'^student/', include(student_urls, namespace='student')),

    url(r'^unit/', include(unit_urls, namespace='unit')),
    url(r'^course/', include(course_urls, namespace='course')),
    url(r'^teacherversion/', include(teacherversion_urls, namespace='teacherversion')),
    url(r'^course_system/', include(course_system_urls, namespace='course_system')),
    url(r'^wechart/', include(wechart_urls, namespace='wechart')),
    url(r'^$', index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jyqj/backend/teacher/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
from django.db import models
from backend.institution.models import City, Institution, CourseSystem


class Teacher(models.Model):
    institution = models.ForeignKey(Institution, verbose_name=u'机构', related_name='teachers')
    city = models.ForeignKey(City, verbose_name=u'城市')
    name = models.CharField(verbose_name=u'名称', max_length=20)
    gender = models.IntegerField(verbose_name=u'性别', default=0)
    mobile = models.CharField(verbose_name=u'电话', max_length=20)
    password = models.CharField(verbose_name=u'密码', max_length=200)
    school_area = models.CharField(verbose_name=u'学校区域', max_length=20)
    create_time = models.BigIntegerField(default=time.time())
    status = models.BooleanField(default=False)
    course_system = models.ManyToManyField(CourseSystem, through='TeacherCourseSystem', verbose_name=u'管理课程体系',
                                           related_name='teachers')

    class Meta:
        db_table = 'tb_teacher'


class TeacherCourseSystem(models.Model):
    teacher = models.ForeignKey(Teacher)
    course_system = models.ForeignKey(CourseSystem)

    class Meta:
        auto_created = True
        db_table = 'tb_teacher_course_system'

jyqj/backend/teacher/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from utils.forms import ChoiceNoValidateField, MultiChoiceNoValidateField
from enumtype import GENDER_TYPE


class TeacherForm(forms.Form):
    """
    teacher
    """
    # institution = ChoiceNoValidateField(label=u'机构')
    city = ChoiceNoValidateField(label=u'城市')
    name = forms.CharField(label=u'名称', max_length=20)
    mobile = forms.CharField(label=u'电话', max_length=20)
    school_area = forms.CharField(label=u'学校区域', max_length=20)
    course_system = MultiChoiceNoValidateField(label=u'可调用课程体系', initial='')

jyqj/backend/teacher/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.conf import settings
from .forms import TeacherForm
from django.db.models import Q
from enumtype import *
from django.contrib import messages
from django.http import Http404
from django.http import HttpResponse, JsonResponse
from utils.baseview import DataTablesView
from .viewmodel import TeacherDQ, TeacherCommand
from backend.accounts.enumtype import LIST_FIELDS as a_list
from backend.accounts.viewmodel import AdminDQ, UserCommand
from backend.operation_log.viewmodel import OperationLogCommand

import traceback

t_dir = 'teacher/'
t_module = '教师'

def teacher_list(request):
    http_content = {
        'title': u'教师列表',
        'list_fields': LIST_FIELDS,
        'searches': {},
        'qry_items': QUERY_TYPE,
    }
    return render(request, t_dir + 'teacher_list.html', http_content)


def get_teacher_by_mobile(request):
    mobile = request.GET.get('mobile', '')
    data = {'name': TeacherCommand.get_teacher_by_mobile(mobile).get('name', '')}
    return JsonResponse(data, safe=False)


def teacher_edit(request, teacher_id=None):
    """
    add ,modify
    """
    selected_city_options = []
    course_system_options = []
    province = {}
    if teacher_id is not None:
        teacher = TeacherCommand().teacher_get(teacher_id)
        selected_city_options = [{
            'id': teacher.get('city', ''),
            'text': teacher.get('city_name', '')
        }]
        course_system_options = TeacherCommand.get_course(teacher_id)
        province = teacher.get('province', {})
    else:
        teacher = None
    action = 'create' if teacher is None else 'modify'
    if request.method == 'POST':
        form = TeacherForm(request.POST, initial=teacher)
        if form.is_valid():
            data = form.cleaned_data
            data['institution_id'] = request.user.accountuser.institution.id
            try:
                # save data----
                teacher_id = TeacherCommand(data=data).teacher_edit(teacher_id)
                if teacher_id == -1:
                    messages.add_message(request, messages.ERROR, u'教师不存在')
                    raise FloatingPointError
                if teacher_id == -2:
                    messages.add_message(request, messages.ERROR, u'该老师已被其他机构添加')
                    raise FloatingPointError
                if teacher_id == -3:
                    messages.add_message(request, messages.ERROR, u'超过该机构的老师数量')
                    raise FloatingPointError
                messages.add_message(request, messages.INFO, u'添加教师成功')
                if action == 'create':
                    OperationLogCommand.operationlog_record(request, t_module, '新建')
                else:
                    OperationLogCommand.operationlog_record(request, t_module, '修改')
                if request.POST.get('_new', None):
                    return redirect('teacher:teacher_create')
                return redirect('teacher:teacher_modify', teacher_id)
            except Exception as e:
                traceback.print_exc()
                form.add_error(None, u'保存出错')
    else:
        form = TeacherForm(teacher)
    print selected_city_options
    print course_system_options
    http_content = {
        'title': u'新增教师' if teacher_id is None else u'教师详情页',
        'action': action,
        'form': form,
        'selected_city_options': selected_city_options,
        'course_system_options': course_system_options,
        'province': province,
        'all_ready_only': not request.user.accountuser.type,
    }
    return render(request, t_dir + 'teacher_form.html', http_content)


class TeacherDTView(DataTablesView):
    need_count = True
    global_fields = [
        'id',
        'name',
        'mobile',
    ]
    rpc_api = TeacherDQ().process

    def do_exra(self, request):
        admin_type = request.user.accountuser.type
        if admin_type == 1:
            self.rpc_api = TeacherDQ(init_q=Q(institution_id=request.user.accountuser.institution.id)).process


def course_system_choices_v(request):
    q = request.GET.get('q', '')
    page = int(request.GET.get('page', 1))
    num = int(request.GET.get('num', 30))
    insti_id = request.user.accountuser.institution.id
    data = TeacherCommand.course_system_choices(q, page, num, insti_id)
    print insti_id, data
    return JsonResponse(data, safe=False)

jyqj/templates/teacher/teacher_form.html
{% extends "base_form.html" %}

{% block form_body %}
{% macro form_select_connect(field, province, ajax_url, selected_options,label_class='', input_class='', attrs=None, multiple=false) -%}
    {# form-select #}
<label{% if label_class %} class="{{ label_class }}"{% endif %} for="{{ field.id_for_label }}">{% if field.field.required %}<span class="text-danger">*</span> {% endif %}省份:</label>
<div class="{{ input_class }}"><select class="form-control select2-remote" id="province" name="province"  data-ajax--url="{{ url('institution:province_choices') }}"  data-allow-clear="true" {% if field.html_name in readonly_fields or 'all' in readonly_fields  %}disabled{% endif %} data-placeholder="-----" {{attrs}}>
        {% if field.value() %}

                <option value="{{ province.id }}" selected="selected">{{ province.text }}</option>

        {% endif %}
    </select></div>
{{ field_label(field, label_class) }}
<div class="{{ input_class }}{% if field.errors %} has-error{% endif %}">
     <select class="form-control select2-remote{% if multiple %}-multiple{% endif %}" id="{{ field.id_for_label }}" name="{{ field.html_name }}" {% if multiple %}multiple="multiple"{% endif %}   data-allow-clear="true" {% if field.html_name in readonly_fields or 'all' in readonly_fields  %}disabled{% endif %} data-placeholder="-----" {{attrs}}>
        {% if field.value() %}
            {% for opt in selected_options %}
                <option value="{{ opt.id }}" selected="selected">{{ opt.text }}</option>
            {% endfor %}
        {% endif %}
    </select>
    {% if field.html_name in readonly_fields or 'all' in readonly_fields  %}
        {% if isinstance(field.value(), list) %}
            {% for val in field.value() %}
            <input type="hidden" name="{{ field.html_name }}" value="{{ val }}">
            {% endfor %}
        {% else %}
            <input type="hidden" name="{{ field.html_name }}" value="{{ field.value() or '' }}">
        {% endif %}
    {% endif %}
    {{ field_error(field) }}
</div>
{%- endmacro %}


<form class="form-horizontal" role="form" method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
     <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                {% if form.non_field_errors() %}<div class="alert alert-danger" role="alert">{{ form.non_field_errors()|join('|') }}</div>{% endif %}

                {% set messages = get_messages(request) %}
                {% if messages %}
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    {{ messages|join('|') }}
                </div>
                {% endif %}
                <div class="form-group">
                    {{ form_input(form.mobile, "col-sm-2 control-label", "col-sm-2") }}
                    {{ form_input(form.name, "col-sm-2 control-label", "col-sm-2") }}

                </div>

               <div class="form-group">
                    {{ form_select_connect(form.city, province, url('institution:city_choices'), selected_city_options,"col-sm-2 control-label", "col-sm-2", attrs=None) }}
                    </div>

                <div class="form-group">
                    {{ form_input(form.school_area, "col-sm-2 control-label", "col-sm-4") }}
                </div>
                <div class="form-group">
                        {{ form_select2(form.course_system, url('teacher:course_system_choices'), course_system_options,"col-sm-2 control-label", "col-sm-4", multiple=true, attrs=None, ) }}
                    </div>
                {% if request.user.accountuser.type ==1 %}
                <div class="col-lg-12 col-lg-offset-2">

                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
                {% endif %}

            </div>
        </div>
     </div>
</form>


{% endblock form_body %}

{% block body_js %}

    <script type="text/javascript" src="http://cdn.staticfile.org/Plupload/2.1.1/plupload.full.min.js"></script>
    <script type="text/javascript" src="{{ static('lib/js/qiniu.min.js') }}"></script>
    <script type="text/javascript" src="{{ static('lib/js/jquery.md5.js') }}"></script>
    <script type="text/javascript" src="{{ static('lib/js/select2.min.js') }}"></script>
    <script src="{{ static('js/hera-select2.js') }}"></script>
    <script type="text/javascript">
    $('#id_mobile').blur(function () {
        var mobile = $('#id_mobile').val();
        var url = "{{url('teacher:teacher_name' )}}" + "?mobile=" + mobile;
        $.getJSON(url, function (data) {
            //var res = JSON.stringify(data);
            console.log(data.name);
            $('#id_name').val(data.name);

            //alert(res);

        })
    })


    function BindSelect(ctrlName, url, is_start) {
    var control = $('#' + ctrlName);
    //绑定Ajax的内容
    $.getJSON(url, function (data) {
        control.empty();//清空下拉框
        var res = JSON.stringify(data);
        //alert(res);
        control.select2({
            allowClear: true,
            data:data.results,
            placeholder:'-------',
            formatResult: function(obj){return obj[opts.textField]},
            formatSelection: function(obj){return obj[opts.textField]},
            escapeMarkup: function (m) {
                return m;
        }

        });
        if(!is_start){
           control.val('');
        }
        else{
            control.val('{{form.city.value() }}');
        }
        control.change();
    });
}

 function InitDictItem() {
            var Name = $("#province").val() | '';
                BindSelect("id_city", "{{url('institution:city_choices' )}}"+ "?province=" + Name, true);
            $("#province").on("change", function (e) {
                var Name = $("#province").val() | '';
                BindSelect("id_city", "{{url('institution:city_choices' )}}"+ "?province=" + Name, false);
            });
        }
InitDictItem();
    </script>

{% endblock %}

jyqj/templates/teacher/teacher_list.html
{% extends "base_list.html" %}

{% block more_filter -%}
<div class="form-group">
    <label class="col-sm-2 control-label">状态:</label>
    <div class="col-sm-2">
    <select id="status" name="status" class="form-control">
        <option value="">全部</option>
        <option value="0">正常</option>
        <option value="1">冻结</option>
    </select>
    </div>
</div>
{%- endblock more_filter %}

{% block list_body %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row mbh">

                    <div class="col-sm-12 dataTables_filter">
                        {% if request.user.accountuser.type ==1 %}
                        <a href="{{ url('teacher:teacher_create') }}" class="btn btn-primary">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            新增
                        </a>
                        {% endif %}
                    </div>

                    </div>

                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="dataTables">
                            <thead>
                            <tr>
                                <th>教师ID</th>
                                <th>姓名</th>
                                <th>手机号码</th>
                                <th>城市</th>
                                <th>校区</th>
                                <th>创建时间</th>
                                <th>状态</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                            <tbody id="id-list">
                            </tbody>
                        </table>
                    </div>
                    <!-- /.dataTable_wrapper -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div> <!-- /.row -->
{% endblock list_body %}

{% block body_js %}
<script type="text/javascript">
    function reset_status(id) {
        bootbox.confirm({
            size: "small",
            title: "冻结状态",
            message: "确认更改",
            callback: function (result) {
                if(result){
                    $.ajax({
                        type: "POST",
                        url: "/institution/reset_teacher_status/",
                        data: {
                            "id": id,
                            "csrfmiddlewaretoken": "{{ csrf_token }}",
                        },
                        dataType: "json",
                        success: function (data) {
                            search();
                        },
                    });
                }
            }
        });
    }
$(document).ready(function () {
    var table = $('#dataTables').dataTable({
        "dom": 'ltpr',
        "language": {
            "url": "{{ static('lib/js/dataTable.Chinese.json') }}"
        },
        "responsive": true,
        "lengthChange": false,
        "serverSide": true,
        "ajax": {
            url: "/teacher/datatable/",
            type: "POST",
            data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
        },
        "columns": {{ list_fields.to_json()|safe }},
        "searchCols": [
            {% for col in list_fields.to_list() -%}
            {% if col.name in searches -%}
            {{ searches[col.name]|jsonify|safe }},
            {% else %}
            null,
            {%- endif %}
            {%- endfor %}
        ],
        "columnDefs": [
            {
                "targets": [7],
                 "render": function ( data, type, full, meta ) {
                    var s = full.status;
                    var status_show = '冻结';
                    if (s=='已冻结'){
                        status_show = '解冻';
                    }
                     return '<a href="/teacher/teacher_list/teacher_modify/'+data+'">{% if request.user.accountuser.type ==1 %}编辑{% else%}详情{%endif%}</a>&nbsp;&nbsp;' +

                         {% if request.user.accountuser.type ==1 %}'<a href="#" onclick="reset_status('+data+')">'+ status_show+'</a>&nbsp;'{%else%}''{%endif%};
                },
            },
        ],
        "order": [[0, 'desc']],
        "processing": true,
        "deferRender": true,
        {#
        {% if not searches -%}
        "deferLoading": true,
        {%- endif %}
        #}
        "pageLength": 10,
    });


    $('#function').change(function(){
        var $selAll = $('#select-allpage');
        if($(this).val()=='set_refunded'){
            $selAll.removeAttr('checked');
            $selAll.attr('disabled','disabled');
        }else{
            $('#select-allpage').removeAttr('disabled');
        }
    });
    //=== search click ===
    $("#id-search-btn").on("keyup click", function () {
        search();
    });

    $("#id-th-checkbox").on("change", function () {
        $("#id-list").find("input[type=checkbox]").prop("checked", $(this).prop("checked"));
    });


    $("#select-allpage").on("click", function () {
        $("#id-th-checkbox").prop("checked", $("#select-allpage").prop("checked"));
        $("#id-list").find("input[type=checkbox]").prop("checked", $("#select-allpage").prop("checked"));
    });

});
</script>

{% endblock %}